# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: sulmaimech
# Description of the Site
description: Welcome to my personal blog!
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Personal, Blog, Portfolio, CV, Resume, sulmaimech, soulaiman, software, cloud engineering, APIs
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: sulaiman.maimuni@gmail.com
facebook_username: 
twitter_username: sulmaimech
instagram_username: sulmaimech
linkedin_username: sulmaimech
github_username:  sulmaimech
youtube_channel_id: UCxATQvqpVoLymZiK1uOY3nw
reddit_username: 
behance_username: 
dribbble_username:
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Soulaiman El Maimouni Mechbal
# URL for the Image of the Author
author-image: assets/images/profile-image.png
# 60 Words About the Author
author-about: >
  Hi, I'm Soulaiman, a software engineer with three years of experience, passionate about cloud-native technologies, DevOps, and building scalable solutions. I'm focused on deepening my expertise in software architecture and aspire to lead impactful projects in the future. Outside of tech, I enjoy boxing, cycling, and Studio Ghibli films, which inspire my love for creativity. I'm also deeply interested in the intersection of tech and finance, exploring how innovation can drive financial growth. Fluent in Spanish, English, Arabic, and French, I value connecting with diverse people. Reach out if we share similar interests!

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/sulmaimmech

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
